color: null
fieldLayouts:
  81df8f37-a845-4283-b8b8-990f1df49119:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-11T01:14:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 799d13da-9f1e-46af-93f2-5ec986531e97
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T01:17:01+00:00'
            elementCondition: null
            fieldUid: 3b105930-d90a-46dc-b6b9-9af6e6f79b07 # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed68e059-f1e3-4d8e-b111-56f0d5f903fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T01:17:01+00:00'
            elementCondition: null
            fieldUid: 87b48b24-95b9-4758-abda-0f104885c7ca # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55e82489-28b6-49d3-a458-9f8006210b96
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T01:17:01+00:00'
            elementCondition: null
            fieldUid: 1db34d3e-6863-40d5-9e01-b37e24926ae9 # Background Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a5e892d-3b83-4452-9af4-8e6a7150811c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T01:17:01+00:00'
            elementCondition: null
            fieldUid: e57c96e1-e4af-4fd1-9692-376349212ce1 # Background Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1a3ae84-d9c7-4352-bfb3-e5eae8c6b8fb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 931e14ec-531b-4390-9013-ee76861e32e0
        userCondition: null
handle: interior
hasTitleField: false
icon: subtitles
name: Interior
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
