color: null
fieldLayouts:
  7ed44808-89b3-4f5f-a502-af4e8e4e45e9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-11T02:29:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e5a0d5e1-71a9-4fa0-af3e-077a7d2e1653 # Link Type
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39b6845e-1387-4e72-80a0-71af3d95d0c2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T02:30:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c69a543-e926-4875-8f7f-81b29a45538f # URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 657d745d-b65f-4b91-90a8-597e301e9639
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 56e790d0-14af-4385-973b-1407a4a6f409
        userCondition: null
handle: link
hasTitleField: false
icon: null
name: Link
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
