color: null
fieldLayouts:
  fd51dd6a-f2e5-4692-8780-95f3975ef91c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-11T01:38:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 93de99b2-1ec3-46ff-8e3e-7b15340351d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T01:40:08+00:00'
            elementCondition: null
            fieldUid: 3b105930-d90a-46dc-b6b9-9af6e6f79b07 # Header
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 274dace7-d653-4da7-85ed-0ee84c34eaf8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T01:40:08+00:00'
            elementCondition: null
            fieldUid: ce984606-e569-4545-8d76-bbc8b17602a0 # Intro
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2776e150-cf29-40b3-b7c4-2bbe72c23487
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68f57969-45c7-4266-ad0a-cea58eadace4
        userCondition: null
handle: quote
hasTitleField: false
icon: ''
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{header}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
