color: null
fieldLayouts:
  2e43bf44-5ac7-4683-bc87-cfcbb48879cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-11T01:24:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 092d12ff-747a-4faa-bf3a-2e5a17f7079f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-11T01:26:20+00:00'
            elementCondition: null
            fieldUid: 690c6206-1642-44f8-bb7a-43307b9cf078 # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 647e6d35-48e9-4713-aa07-11bbed16387e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9b589945-5c00-42c4-ab1f-339b58f2b496
        userCondition: null
handle: simpleLinks
hasTitleField: false
icon: link
name: 'Simple Links'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
