headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Default
options:
  alignment:
    options:
      - left
      - center
      - right
  fontFamily:
    options:
      - default
      - "'Raleway', sans-serif"
  fontSize:
    options:
      - 12
      - 14
      - 16
      - 18
      - 20
      - 24
      - 30
      - 36
      - 40
  style:
    definitions:
      -
        classes:
          - red-heading
        element: h2
        name: 'Red heading'
      -
        classes:
          - vibrant-code
        element: pre
        name: 'Vibrant code'
      -
        classes:
          - marker
        element: span
        name: Marker
toolbar:
  - undo
  - redo
  - sourceEditing
  - '|'
  - fontFamily
  - fontSize
  - style
  - heading
  - '|'
  - alignment
  - '|'
  - blockQuote
  - code
  - codeBlock
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
  - subscript
  - superscript
  - '|'
  - bulletedList
  - numberedList
  - outdent
  - indent
  - horizontalLine
  - '|'
  - link
  - anchor
  - '|'
  - insertImage
  - mediaEmbed
  - insertTable
  - htmlEmbed
  - createEntry
