altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  d4e44d1c-eeb4-4869-813c-8e97a05dc199:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-10T21:30:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 152b9e15-798c-4ec5-a411-daead2caa64e
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-10T21:31:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 794acedc-f7d1-4ec3-b8a5-913fed831c48
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ef4c01a-84e9-4a87-8fbc-ef08d84aeab7
        userCondition: null
fs: localUploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: localUploads
transformSubpath: ''
