columnSuffix: null
handle: intro
instructions: null
name: Intro
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 7d0d1866-c791-4d01-bdd0-7f776c670f00 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
