columnSuffix: null
handle: links
instructions: null
name: Links
searchable: false
settings:
  contentTable: ''
  createButtonLabel: null
  entryTypes:
    - 997c67a6-6ae1-47fa-a533-e2c515fc005a # Links
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
