defaultPlacement: end
enableVersioning: true
entryTypes:
  - 238af70c-5f6a-42fc-a0c6-ac969bda13b2 # Pages Default
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  b53c7a52-6b00-4580-ac7c-c9e3eb83dae5: # Words Breathe
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: d0f569ea-4580-42ce-b300-e79caf531ab0
type: structure
